export const UPDATE_GLOBAL_OPERATION_OVERLAY_STATUS =
  "UPDATE_GLOBAL_OPERATION_OVERLAY_STATUS";
export const UPDATE_GLOBAL_OPERATION_NOTIFICATION_STATUS =
  "UPDATE_GLOBAL_OPERATION_NOTIFICATION_STATUS";
